agent: 'master' # This will be the default agent

workflow:
  - branch: 'default'
    steps: 
      - notification:
          stage_name: 'INITIAL SCM NOTIFICATION'
          checkout_scm: true
          clean_up_workspace: false
          notification_type: 'SCM'
          in_progress: true
      - maven:
          stage_name: 'MAVEN BUILD'
          checkout_scm: false
          clean_up_workspace: false
          maven_operation_type: 'BUILD'
          maven_command: 'mvn clean package'
      - notification:
          stage_name: 'FINAL SCM NOTIFICATION'
          checkout_scm: false
          clean_up_workspace: true
          notification_type: 'SCM'
          in_progress: false
  - branch: 'feature'
    steps: 
      - notification:
          stage_name: 'INITIAL SCM NOTIFICATION'
          checkout_scm: true
          clean_up_workspace: false
          notification_type: 'SCM'
          in_progress: true
      - maven:
          stage_name: 'MAVEN BUILD'
          checkout_scm: false
          clean_up_workspace: false
          maven_operation_type: 'BUILD'
          maven_command: 'mvn clean package -DskipTests=true'
      - notification:
          stage_name: 'FINAL SCM NOTIFICATION'
          checkout_scm: false
          clean_up_workspace: true
          notification_type: 'SCM'
          in_progress: false
